TK/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daftar-kontributor/', include('daftar_kontributor.urls')),
    path('langganan/', include('langganan.urls')),
    path('authentication/', include('authentication.urls')),
    path('', include('tayangan.urls')),
    path('daftar-unduhan/', include('daftar_unduhan.urls')),
    path('daftar-favorit/', include('daftar_favorit.urls'))
]

authentication/urls.py
from django.urls import path
from authentication.views import landing, login_view, logout_view, register_view

app_name = 'authentication'

urlpatterns = [
     path('', landing, name='landing'),
     path('login/', login_view, name='login_view'),
     path('register/', register_view, name='register_view'),
     path('logout/', logout_view, name='logout'),
]

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.db import connection, InternalError
from django.contrib import messages

# Create your views here.
def landing(request):
    return render(request, 'landing.html')

def login_view(request):
     context = {}
     if request.method == 'POST':
          username = request.POST.get('username')
          password = request.POST.get('password')

          print(username)
          with connection.cursor() as cursor:
               cursor.execute(f"""SELECT username, password FROM "PENGGUNA" WHERE username = %s AND password = %s""", 
                              [username, password])
               user = cursor.fetchone()
          
          if user is not None:
               request.session['username'] = username
               response = redirect('tayangan:show_tayangan')
               response.set_cookie('username', username)
               return response
          else:
               context['error'] = "Username atau password tidak ditemukan"
               messages.error(request, "Username atau password tidak ditemukan")
     return render(request, 'login_page.html', context)

def register_view(request):
     if request.method == "POST":
          username = request.POST['username']
          password = request.POST['password']
          negara_asal = request.POST['negara_asal']
          
          cursor = connection.cursor()
          try:
               cursor.execute(f"""
                    INSERT INTO "PENGGUNA" VALUES ('{username}', '{password}', '{negara_asal}');
               """)
               messages.success(request, 'Registrasi berhasil! Silahkan login')
          except InternalError as e:
               if 'Username' in str(e):
                    messages.error(request, f"Username {username} sudah terdaftar!")
     return render(request, 'register_page.html')

def logout_view(request):
     logout(request)
     return redirect('authentication:landing')

authentication/templates/landing.html
{% extends "base-tw.html" %}

{% block meta %}
<title>PacilFlix - 8</title>
{% endblock meta %}

{% block content %}
<style>
    .center-screen {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100vh;
        gap: 20px;
    }

    h1 {
        font-family: 'Roboto', sans-serif !important;
        font-size: 3rem;
        font-weight: 400;
        line-height: 1.5;
        color: #6f99c0;
    }
    
    .button {
        background-color: rgb(211, 211, 211);
        color: black;
        cursor: pointer;
        font-size: 1rem;
        text-align: center;
        border: 2px solid #000; /* Menambahkan border dengan warna hitam */
        padding: 10px 10px; /* Menambahkan padding ke tombol */
    }
</style>

{% include "navbar.html" %}
<div class="center-screen"> 
    <h1>PacilFlix - 8</h1>
    <a href="{% url 'authentication:login_view' %}" class="button"><button>Login</button></a>
    <a href="{% url 'authentication:register_view' %}" class="button"><button>Register</button></a>
</div>
{% endblock content %}

authentication/templates/login_page.html
{% extends 'base-tw.html' %}

{% block meta %}
     <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
     .login {
         display: flex;
         flex-direction: column;
         justify-content: center;
         align-items: center;
         height: 100vh;
         gap: 20px;
     }

     h1 {
          font-family: 'Roboto', sans-serif !important;
          font-size: 2rem;
          font-weight: 400;
          line-height: 1.5;
          color: #6f99c0;
     }

     .form-control{
          padding: 8px; /* Tambahkan padding ke input */
          border: 1px solid #ccc; /* Tambahkan border */
          border-radius: 5px; /* Tambahkan border-radius untuk sudut yang lebih lembut */
          width: 200px; /* Tentukan lebar input */
          margin: 5px;
     }

     .button {
          background-color: rgb(211, 211, 211);
          color: black;
          cursor: pointer;
          font-size: 1rem;
          text-align: center;
          border: 2px solid #000; /* Menambahkan border dengan warna hitam */
          padding: 10px 10px; /* Menambahkan padding ke tombol */
     }

</style>

{% include "navbar.html" %}
<div class = "login">

     <h1>FORM LOGIN</h1>

     <form method="POST">
          {% csrf_token %}
          <table>
               <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
               </tr>
                         
               <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
               </tr>

               <tr>
                    <td></td>
                    <td><input type="submit" name="submit" class="button" value="MASUK"/></td> 
               </tr>
          </table>
     </form>

     {% if messages %}
          <ul class="messages">
               {% for message in messages %}
                    <li>{{ message }}</li>
               {% endfor %}
          </ul>
     {% endif %}   
</div>

{% endblock content %}

authentication/templates/register_page.html
{% extends 'base-tw.html' %}

{% block meta %}
     <title>Register</title>
{% endblock meta %}

{% block content %}  
<style>
     .register {
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          height: 100vh;
          gap: 20px;
     }  

     h1 {
          font-family: 'Roboto', sans-serif !important;
          font-size: 2rem;
          font-weight: 400;
          line-height: 1.5;
          color: #6f99c0;
     }

     .form-control{
          padding: 8px; /* Tambahkan padding ke input */
          border: 1px solid #ccc; /* Tambahkan border */
          border-radius: 5px; /* Tambahkan border-radius untuk sudut yang lebih lembut */
          width: 200px; /* Tentukan lebar input */
          margin: 5px;
     }

     .button {
          background-color: rgb(211, 211, 211);
          color: black;
          cursor: pointer;
          font-size: 1rem;
          text-align: center;
          border: 2px solid #000; /* Menambahkan border dengan warna hitam */
          padding: 10px 10px; /* Menambahkan padding ke tombol */
     }
</style>

{% include "navbar.html" %}
<div class="register">

     <h1>FORM REGISTRASI</h1>  

     <form method="POST">  
          {% csrf_token %}  
          <table>  
               <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" required placeholder="Username" class="form-control" maxlength="50"></td>
               </tr>
               <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" required placeholder="Password" class="form-control" maxlength="50"></td>
               </tr>
               <tr>
                    <td>Negara Asal: </td>
                    <td><input type="text" name="negara_asal" required placeholder="Negara Asal" class="form-control" maxlength="50"></td>
               </tr>
               <tr>
                    <td></td>
                    <td><input type="submit" name="submit" class="button" value="DAFTAR"/></td> 
               </tr>  
          </table>  
     </form>

     {% if messages %}
          <ul class="messages">
               {% for message in messages %}
                    <li class="{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
               {% endfor %}
          </ul>
     {% endif %} 
</div>  
{% endblock content %}