TK/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daftar-kontributor/', include('daftar_kontributor.urls')),
    path('langganan/', include('langganan.urls')),
    path('authentication/', include('authentication.urls')),
    path('', include('tayangan.urls')),
    path('daftar-unduhan/', include('daftar_unduhan.urls')),
    path('daftar-favorit/', include('daftar_favorit.urls'))
]

daftar_unduhan/urls.py
from django.urls import path
from daftar_unduhan.views import show_download, hapus_unduhan

app_name = 'daftar_unduhan'

urlpatterns = [
  path('download/', show_download, name='show_download'),
  path('download/hapus/<str:id>/<str:timestamp>', hapus_unduhan, name='hapus_unduhan'),
]

daftar_unduhan/models.py
from django.db import models

# Create your models here.

daftar_unduhan/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.db import DatabaseError, Error, InternalError, connection
from django.urls import reverse

# Create your views here.
def show_download(request):
    with connection.cursor() as cursor:
        logged_in_username = request.session.get('username')
        cursor.execute(f"""SELECT t.id, t.judul, tt.timestamp 
                            FROM "TAYANGAN" t
                            JOIN "TAYANGAN_TERUNDUH" tt ON t.ID = tt.ID_TAYANGAN
                            WHERE USERNAME = '{logged_in_username}'
                    """)
        tayangan_yg_terunduh = cursor.fetchall()
        
        id = []
        judul = []
        timestamp = []
        for row in tayangan_yg_terunduh:
            id.append(row[0])
            judul.append(row[1])
            timestamp.append(row[2])
        print(id)
        print(judul)
        print(timestamp)  
        
        complete_detail = zip(id, judul, timestamp)
            
        context = {
            'tayangan_yg_terunduh': complete_detail
        }
    return render(request, 'daftar_unduhan.html', context)

def hapus_unduhan(request, id, timestamp):
    logged_in_username = request.session.get('username')
    
    if logged_in_username:
                    try:
                        with connection.cursor() as cursor:
                            cursor.execute(f"""DELETE FROM "TAYANGAN_TERUNDUH" 
                                            WHERE id_tayangan = '{id}'
                                            AND username = '{logged_in_username}' AND timestamp = '{timestamp}'
                                            """)
                            messages.info(request, 'Tayangan berhasil dihapus dari daftar unduhan.')
                            return HttpResponseRedirect(f'/daftar-unduhan/download/')

                    except Error as e:
                        messages.info(request, 'Tayangan minimal harus berada di daftar unduhan selama 1 hari agar bisa dihapus.')
                        return HttpResponseRedirect(f'/daftar-unduhan/download/')


    else:
        return JsonResponse({'status': 'error', 'message': 'User not authenticated'}, status=401)

daftar_unduhan/templates/daftar_unduhan.html
{% extends "base-tw.html" %}
{% load static %}

{% block meta %}
<title>Daftar Unduhan</title>
{% endblock meta %}

{% block content %}
<style>
   .custom-scrollbar::-webkit-scrollbar {
        width: 2px;
    }

    /* Track */
    .custom-scrollbar-white::-webkit-scrollbar-track {
        background: white !important;
        border-radius: 0px;
    }
    .custom-scrollbar-gray::-webkit-scrollbar-track {
        background: rgb(209 213 219) !important;
        border-radius: 0px;
    }

    /* Handle scrollbar*/
    .custom-scrollbar::-webkit-scrollbar-thumb {
        background: #888;
        border-radius: 10px;
        border: 5px solid white;
    }
    .custom-scrollbar-white::-webkit-scrollbar-thumb {
        background: #888;
        border-radius: 10px;
        border: 5px solid white;
    }
    .custom-scrollbar-gray::-webkit-scrollbar-thumb {
        background: #888;
        border-radius: 10px;
        border: 5px solid rgb(209 213 219);
    }

    /* Handle on hover */
    .custom-scrollbar::-webkit-scrollbar-thumb:hover {
        background: #555;
    }

    .top-header {
    background-color: #2986cc !important; /* Change this to the color you want */
  }

    .delete-button {
    background-color: #f06056; /* Red */
    color: white;
    padding: 15px 32px;
    text-align: center;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    border-radius: 12px;
  }

  .container {
        margin-top: 5px; /* Adjust this value based on your navbar height */
    }

    /* Handle on html */
    body {
        /* display: flex; */
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        font-family: Arial, sans-serif;
        padding-top: 86px;
    }
    table, th, td {
        border: 1px solid black;
    }
    th {
        background-color: #2986cc;
        padding: 5px;
        color: white;
    }
    td {
        padding: 5px;
        border-bottom: 1px solid #ddd;
    }
    table#favoriteTable {
        width: 100%;
        border-collapse: collapse;
    }

    table#favoriteTable th,
    table#favoriteTable td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center;
    }
    table#favoriteTable tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    table#favoriteTable th {
        background-color: #434446;
        color: white;
    }
    select {
        margin-bottom: 10px;
    }
    h1 {
        text-align: center; 
        font-weight: bold; 
        font-size: 2rem; 
    }
</style>

{% include "navbar.html" %}
<div class="container">
    <div>
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    </div>
        <table id="favoriteTable">
        <thead>
            <tr>
                <th class="top-header" colspan="3">Daftar Unduhan</th>
            </tr>
        </thead>
        <thead>
                <th>Judul</th>
                <th>Waktu Diunduh</th>
                <th>Aksi</th>
        </thead>
        <tbody>
                {% for i, j, k in tayangan_yg_terunduh %}
                <tr>
                    <td>{{ j }}</td>
                    <td>{{ k }}</td>
                    <td>
                            <a href="{% url 'daftar_unduhan:hapus_unduhan' i k %}" id="deleteFromfav">
                            <button type="button" class="delete-button" id="{{ k }}" data-bs-toggle="modal" data-bs-target="#messageModal">Hapus</button>
                            </a>
                        </td>

                    </a>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="modal fade" id="messageModal" tabindex="-1" aria-labelledby="messageModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                        <h1 class="modal-title fs-5" id="messageModalLabelTitle"> JUDUL</h1>
                </div>
                <div class="modal-body" id="downloadModalBody"></div>
                    <p>
                    </p>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
<script>
    var deleteButtons = document.getElementsByClassName('delete-button');
    for (var i = 0; i < deleteButtons.length; i++) {
        deleteButtons[i].addEventListener('click', function() {
            var waktu = this.getAttribute('id');
            var waktuDatenya = moment(waktu, 'MMMM D, YYYY, h:mm a');
            var hoursToSubtract = 24; // Change this to the number of hours you want to subtract
            var currentTime = moment();
            currentTime.subtract(hoursToSubtract, 'hours');
            if (currentTime.isBefore(waktuDatenya)) {
                document.getElementById('messageModalLabelTitle').innerHTML = 'GAGAL MENGHAPUS TAYANGAN DARI DAFTAR UNDUHAN';
                document.getElementById('downloadModalBody').innerHTML = 'Tayangan minimal harus berada di daftar unduhan selama 1 hari agar bisa dihapus.';
            } else {
                document.getElementById('messageModalLabelTitle').innerHTML = 'SUKSES MENGHAPUS TAYANGAN DARI DAFTAR UNDUHAN';
                document.getElementById('downloadModalBody').innerHTML = 'Tayangan berhasil dihapus dari daftar unduhan.';
            }
        });
    }

</script>

</body>
{% endblock content %}