TK/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daftar-kontributor/', include('daftar_kontributor.urls')),
    path('langganan/', include('langganan.urls')),
    path('authentication/', include('authentication.urls')),
    path('', include('tayangan.urls')),
    path('daftar-unduhan/', include('daftar_unduhan.urls')),
    path('daftar-favorit/', include('daftar_favorit.urls'))
]

daftar_favorit/urls.py
from django.urls import path
from daftar_favorit.views import show_favorite, show_film_in_daftar_favorit, delete_daftar_favorite, delete_from_favorite

app_name = 'daftar_favorit'
urlpatterns = [
    path('fav/', show_favorite, name='show_favorite'),
    path('fav/<str:judul>/', show_film_in_daftar_favorit, name='show_film_in_daftar_favorite'),
    path('fav/hapus/<str:judul>/', delete_daftar_favorite, name='delete_daftar_favorite'),
    path('fav/<str:judul_daftar>/<str:id>/', delete_from_favorite, name='delete_from_favorite'),
]

daftar_favorit/models.py
from django.db import models

# Create your models here.

daftar_favorit/views.py
import datetime
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.db import connection

# Create your views here.

def show_favorite(request):
    logged_in_username = request.session.get('username')
    if logged_in_username:
            with connection.cursor() as cursor:
                cursor.execute(f"""
                               SELECT df.judul, df.timestamp
                               FROM "DAFTAR_FAVORIT" df
                                WHERE
                                df.username = '{logged_in_username}'
                               """)
                tayangan_favoritnya = cursor.fetchall()
                print(tayangan_favoritnya)
                judul_daftar_favorit = []
                timestamp_daftar_favorit = []
                for row in tayangan_favoritnya:
                    judul_daftar_favorit.append(row[0])
                    timestamp_daftar_favorit.append(row[1])
                detail_daftar_favorit = zip(judul_daftar_favorit, timestamp_daftar_favorit)
                context = {
                    'detail_daftar_favorit': detail_daftar_favorit
                }
                return render(request, 'daftar_favorit.html', context)

def show_film_in_daftar_favorit(request, judul):
    logged_in_username = request.session.get('username')
    if logged_in_username:
        with connection.cursor() as cursor:
            cursor.execute(f"""
                           SELECT df.judul
                           FROM "DAFTAR_FAVORIT" df
                           WHERE df.username = '{logged_in_username}' AND df.judul = '{judul}'
                            """)
            list_judul = cursor.fetchall()
            current_time = datetime.datetime.now()
            add_time_gmt_plus_seven = datetime.timedelta(hours=7) 
            current_time_real = current_time + add_time_gmt_plus_seven
            current_time_format = current_time_real.strftime('%Y-%m-%d %H:%M:%S')
            if len(list_judul) == 0:
                cursor.execute(f"""INSERT INTO "DAFTAR_FAVORIT" (username, judul, timestamp)
                                VALUES ('{logged_in_username}', '{judul}', '{current_time_format}')
                                """)
                return redirect(f'/daftar-favorit/fav/')
            else:
                with connection.cursor() as cursor:
                    cursor.execute(f"""
                                SELECT t.judul, t.id
                                FROM "TAYANGAN" t
                                JOIN
                                    "TAYANGAN_MEMILIKI_DAFTAR_FAVORIT" tmf ON t.id = tmf.id_tayangan
                                    JOIN
                                    "DAFTAR_FAVORIT" df ON tmf.timestamp = df.timestamp AND tmf.username = df.username
                                    WHERE
                                    df.username = '{logged_in_username}' AND df.judul = '{judul}'
                                """)
                    list_tayangan = cursor.fetchall()
                    print(list_tayangan)
                    judul_film = []
                    id_film = []
                    for row in list_tayangan:
                        judul_film.append(row[0])
                        id_film.append(row[1])
                    detail_tayangan_di_daftar = zip(judul_film, id_film)
                    context = {
                        'judul_daftar_favorit': judul,
                        'detail_tayangan_di_daftar': detail_tayangan_di_daftar
                    }
                    return render(request, 'detail_daftar_favorit.html', context)

    else:
        return HttpResponse('User not authenticated', status=401)

def delete_from_favorite(request, judul_daftar, id):
    with connection.cursor() as cursor:
        logged_in_username = request.session.get('username')
        cursor.execute(f"""DELETE 
                       FROM 
                       "TAYANGAN_MEMILIKI_DAFTAR_FAVORIT"
                            WHERE id_tayangan IN (
                            SELECT t.id
                            FROM "TAYANGAN" t
                            WHERE t.id = '{id}'
                            )
                            AND 
                            timestamp IN (
                            SELECT d.timestamp
                            FROM "DAFTAR_FAVORIT" d
                            JOIN "PENGGUNA" u ON d.username = u.username
                            WHERE d.judul = '{judul_daftar}' AND u.username = '{logged_in_username}'
                            )
                           """)
        return redirect(f'/daftar-favorit/fav/{judul_daftar}')
    
def delete_daftar_favorite(request, judul):
    with connection.cursor() as cursor:
        logged_in_username = request.session.get('username')
        cursor.execute(f"""DELETE FROM "DAFTAR_FAVORIT"
                           WHERE judul = '{judul}'
                           AND username = '{logged_in_username}'
                           """)
        return redirect(f'/daftar-favorit/fav/')

daftar_favorit/templates/daftar_favorit.html
{% extends "base-tw.html" %}
{% load static %}

{% block meta %}
<title>Daftar Favorit</title>
{% endblock meta %}

{% block content %}
<style>
   .custom-scrollbar::-webkit-scrollbar {
        width: 2px;
    }

    /* Track */
    .custom-scrollbar-white::-webkit-scrollbar-track {
        background: white !important;
        border-radius: 0px;
    }
    .custom-scrollbar-gray::-webkit-scrollbar-track {
        background: rgb(209 213 219) !important;
        border-radius: 0px;
    }

    /* Handle scrollbar*/
    .custom-scrollbar::-webkit-scrollbar-thumb {
        background: #888;
        border-radius: 10px;
        border: 5px solid white;
    }
    .custom-scrollbar-white::-webkit-scrollbar-thumb {
        background: #888;
        border-radius: 10px;
        border: 5px solid white;
    }
    .custom-scrollbar-gray::-webkit-scrollbar-thumb {
        background: #888;
        border-radius: 10px;
        border: 5px solid rgb(209 213 219);
    }

    /* Handle on hover */
    .custom-scrollbar::-webkit-scrollbar-thumb:hover {
        background: #555;
    }

    .top-header {
    background-color: #2986cc !important; /* Change this to the color you want */
  }

    .delete-button {
    background-color: #f06056; /* Red */
    color: white;
    padding: 15px 32px;
    text-align: center;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    border-radius: 12px;
  }

    /* Handle on html */
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
    }
    table, th, td {
        border: 1px solid black;
    }
    th {
        background-color: #2986cc;
        padding: 5px;
        color: white;
    }
    td {
        padding: 5px;
        border-bottom: 1px solid #ddd;
    }
    table#favoriteTable {
        width: 100%;
        border-collapse: collapse;
    }

    table#favoriteTable th,
    table#favoriteTable td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center;
    }
    table#favoriteTable tr:nth-child(even) {
        background-color: #f2f2f2;
    }
    table#favoriteTable th {
        background-color: #434446;
        color: white;
    }
    select {
        margin-bottom: 10px;
    }
    h1 {
        text-align: center; 
        font-weight: bold; 
        font-size: 2rem; 
    }
</style>

{% include "navbar.html" %}
<div class="container">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Tambah Daftar Favorit</button>
        <table id="favoriteTable">
        <thead>
            <tr>
                <th class="top-header" colspan="3">Daftar Favorit</th>
            </tr>
        </thead>
        <thead>
                <th>Judul</th>
                <th>Waktu Dibuat</th>
                <th>Aksi</th>
        </thead>
        <tbody>
                {% for i, j in detail_daftar_favorit %}
                <tr>
                    <td> 
                    <a href="{% url 'daftar_favorit:show_film_in_daftar_favorite' i %}" id="trigger_button">
                        {{ i }} 
                    </a>
                    </td>
                    
                    <td> {{ j }} </td>
                    <td>
                        <a href="{% url 'daftar_favorit:delete_daftar_favorite' i %}">
                            <button type="button" class="delete-button" id="btn-hapus" data-nama="{{ i }}"  onclick="return confirm('Are you sure?');" data-bs-toggle="modal" data-bs-target="#messageModal">Hapus</button>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="modal fade" id="messageModal" tabindex="-1" aria-labelledby="messageModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                        <h1 class="modal-title fs-5" id="messageModalLabelTitle"> JUDUL</h1>
                </div>
                <div class="modal-body" id="downloadModalBody"></div>
                    <p>
                    </p>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
 </div>

 <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah Daftar Favorit</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Judul Daftar Favorit: </label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="" id="tambah_daftar">
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Tambah judul</button>
                </a>
            </div>
        </div>
    </div>
</div>

</div>
  
<script>
   var deleteButtons = document.getElementsByClassName('delete-button');
    for (var i = 0; i < deleteButtons.length; i++) {
        deleteButtons[i].addEventListener('click', function() {
            var judul = this.getAttribute('data-nama');
            var link = this.parentElement.href;
            var modalTitle = document.getElementById('messageModalLabelTitle');
            var modalBody = document.getElementById('downloadModalBody');
            modalTitle.innerHTML = 'Hapus Daftar Favorit';
            modalBody.innerHTML = 'Menghapus daftar favorit ' + judul;
        });
    }

    document.getElementById("button_add").addEventListener("click", function () {
            var judul_daftarnya = document.getElementById("name").value;
            var url = encodeURIComponent(judul_daftarnya) + "/";
            document.getElementById('tambah_daftar').setAttribute('href', url);
        });

</script>
{% endblock content %}

daftar_favorit/templates/detail_daftar_favorit.html
{% extends "base-tw.html" %}
{% load static %}

{% block meta %}
<title>Detail Daftar {{ judul_daftar_favorit }}</title>
{% endblock meta %}

{% block content %}
<style>
    .custom-scrollbar::-webkit-scrollbar {
         width: 2px;
     }
 
     /* Track */
     .custom-scrollbar-white::-webkit-scrollbar-track {
         background: white !important;
         border-radius: 0px;
     }
     .custom-scrollbar-gray::-webkit-scrollbar-track {
         background: rgb(209 213 219) !important;
         border-radius: 0px;
     }
 
     /* Handle scrollbar*/
     .custom-scrollbar::-webkit-scrollbar-thumb {
         background: #888;
         border-radius: 10px;
         border: 5px solid white;
     }
     .custom-scrollbar-white::-webkit-scrollbar-thumb {
         background: #888;
         border-radius: 10px;
         border: 5px solid white;
     }
     .custom-scrollbar-gray::-webkit-scrollbar-thumb {
         background: #888;
         border-radius: 10px;
         border: 5px solid rgb(209 213 219);
     }
 
     /* Handle on hover */
     .custom-scrollbar::-webkit-scrollbar-thumb:hover {
         background: #555;
     }
 
     .top-header {
     background-color: #2986cc !important; /* Change this to the color you want */
   }
 
     .delete-button {
     background-color: #f06056; /* Red */
     color: white;
     padding: 15px 32px;
     text-align: center;
     display: inline-block;
     font-size: 16px;
     margin: 4px 2px;
     border-radius: 12px;
   }
 
     /* Handle on html */
     body {
         display: flex;
         justify-content: center;
         align-items: center;
         height: 100vh;
         margin: 0;
         padding: 0;
         font-family: Arial, sans-serif;
     }
     table, th, td {
         border: 1px solid black;
     }
     th {
         background-color: #2986cc;
         padding: 5px;
         color: white;
     }
     td {
         padding: 5px;
         border-bottom: 1px solid #ddd;
     }
     table#favoriteTable {
         width: 100%;
         border-collapse: collapse;
     }
 
     table#favoriteTable th,
     table#favoriteTable td {
         border: 1px solid #ddd;
         padding: 8px;
         text-align: center;
     }
     table#favoriteTable tr:nth-child(even) {
         background-color: #f2f2f2;
     }
     table#favoriteTable th {
         background-color: #434446;
         color: white;
     }
     select {
         margin-bottom: 10px;
     }
     h1 {
         text-align: center; 
         font-weight: bold; 
         font-size: 2rem; 
     }
 </style>
 
 {% include "navbar.html" %}
 <div class="container">
         <table id="favoriteTable">
         <thead>
             <tr>
                 <th class="top-header" colspan="3" id="judul_daftar">{{ judul_daftar_favorit }}</th>
             </tr>
         </thead>
         <thead>
                 <th>Judul</th>
                 <th>Aksi</th>
         </thead>
         <tbody>
                 {% for i, j in detail_tayangan_di_daftar %}
                 <tr>
                     <td> {{ i }} </td>
                     <td>
                        <a href="{% url 'daftar_favorit:delete_from_favorite' judul_daftar_favorit  j%} " id="link_delete_from_favorite">
                            <button type="button" class="delete-button" data-bs-toggle="modal" data-bs-target="#messageModal" id="{{ i }}">Hapus</button>
                        </a>
                     </td>
                 </tr>
                 {% endfor %}
             </tbody>
         </table>

     </div>
     <div class="modal fade" id="messageModal" tabindex="-1" aria-labelledby="messageModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                        <h1 class="modal-title fs-5" id="messageModalLabelTitle"> JUDUL</h1>
                </div>
                <div class="modal-body" id="downloadModalBody"></div>
                    <p>
                    </p>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
 </div>
   
 <script>
    var deleteButtons = document.getElementsByClassName('delete-button');
    for (var i = 0; i < deleteButtons.length; i++) {
        deleteButtons[i].addEventListener('click', function() {
            var judul = this.id;
            var link = this.parentElement.href;
            var modalTitle = document.getElementById('messageModalLabelTitle');
            var modalBody = document.getElementById('downloadModalBody');
            var namaDaftarFavorit = document.getElementById('judul_daftar').innerHTML;
            modalTitle.innerHTML = 'Hapus dari Daftar Favorit';
            modalBody.innerHTML = 'Menghapus ' + judul + ' dari ' + namaDaftarFavorit;;
        });
    }

 </script>
 {% endblock content %}