TK/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daftar-kontributor/', include('daftar_kontributor.urls')),
    path('langganan/', include('langganan.urls')),
    path('authentication/', include('authentication.urls')),
    path('', include('tayangan.urls')),
    path('daftar-unduhan/', include('daftar_unduhan.urls')),
    path('daftar-favorit/', include('daftar_favorit.urls'))
]

daftar_unduhan/urls.py
from django.urls import path
from daftar_unduhan.views import show_download, hapus_unduhan

app_name = 'daftar_unduhan'

urlpatterns = [
  path('download/', show_download, name='show_download'),
  path('download/hapus/<str:id>/<str:timestamp>', hapus_unduhan, name='hapus_unduhan'),
]

tayangan/urls.py
from django.urls import path
from tayangan.views import (show_trailer, show_tayangan, show_hasil_pencarian_trailer, show_hasil_pencarian_tayangan,
                            show_film, show_series, show_episode, unduh_tayangan, tambah_ke_daftar_favorit,
                            add_ulasan, add_tonton)
app_name = 'tayangan'

urlpatterns = [
    path('', show_trailer, name='show_trailer'),
    path('tayangan/', show_tayangan, name='show_tayangan'),
    path('hasil-pencarian-trailer/<str:value>/', show_hasil_pencarian_trailer, name='show_hasil_pencarian_trailer'),
    path('hasil-pencarian-tayangan/<str:value>/', show_hasil_pencarian_tayangan, name='show_hasil_pencarian_trailer'),
    path('tayangan/film/<str:id>/', show_film, name='show_film'),
    path('tayangan/series/<str:id>/', show_series, name='show_series'),
    path('tayangan/series/<str:id>/<str:sub_judul>/', show_episode, name='show_episode'),
    path('unduh/<str:id>/', unduh_tayangan, name='unduh_tayangan'),
    path('tayangan/film/<str:id>/<str:judul>/', tambah_ke_daftar_favorit, name='tambah_ke_favorit'),
    path('tayangan/add-ulasan/', add_ulasan, name='add_ulasan'),
    path('tayangan/add-tonton/', add_tonton, name='add_tonton'),
]

tayangan/views.py
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import render
from django.contrib import messages
from django.db import connection, InternalError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from function.general import *
from urllib.parse import quote
import datetime

def show_trailer(request):
    if 'username' in request.session and 'username' in request.COOKIES:
        return redirect('tayangan:show_tayangan')

    top_10 = query_result(f"""WITH durasi_tayangan AS (
                            SELECT T.id AS id, F.durasi_film AS durasi
                            FROM "TAYANGAN" AS T
                            JOIN "FILM" AS F ON F.id_tayangan = T.id
                            UNION
                            SELECT T.id AS id, SUM(E.durasi) AS durasi
                            FROM "TAYANGAN" AS T
                            JOIN "SERIES" AS S ON S.id_tayangan = T.id
                            JOIN "EPISODE" AS E on E.id_series = T.id
                            GROUP BY T.id
                        ), recent_views AS (
                            SELECT T.id AS id, EXTRACT(EPOCH FROM (RW.end_date_time - RW.start_date_time)) / 60 AS watch_time
                            FROM "TAYANGAN" AS T 
                            JOIN "FILM" AS F ON F.id_tayangan = T.id
                            JOIN "RIWAYAT_NONTON" AS RW ON RW.id_tayangan = T.id
                            WHERE RW.start_date_time >= NOW() - INTERVAL '7 DAYS'
                            UNION
                            SELECT T.id AS id, SUM(EXTRACT(EPOCH FROM (RW.end_date_time - RW.start_date_time)) / 60) AS watch_time
                            FROM "TAYANGAN" AS T
                            JOIN "SERIES" AS S ON S.id_tayangan = T.id
                            JOIN "EPISODE" AS E ON E.id_series = T.id
                            JOIN "RIWAYAT_NONTON" AS RW ON RW.id_tayangan = T.id
                            WHERE RW.start_date_time >= NOW() - INTERVAL '7 DAYS'
                            GROUP BY T.id, RW.username
                        )
                        
                        SELECT T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer, COUNT(*) as total_view
                        FROM "TAYANGAN" AS T
                        JOIN "durasi_tayangan" AS DT ON DT.id = T.id
                        JOIN "recent_views" AS RV ON RV.id = T.id
                        WHERE RV.watch_time > (0.7 * DT.durasi)
                        GROUP BY T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer
                        ORDER BY total_view DESC, T.judul ASC
                        LIMIT 10;""")

    film = query_result(f"""SELECT T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer
                            FROM "TAYANGAN" AS T
                            JOIN "FILM" AS F ON F.id_tayangan = T.id;""")

    series = query_result(f"""SELECT T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer
                            FROM "TAYANGAN" AS T
                            JOIN "SERIES" AS S ON S.id_tayangan = T.id;""")

    rank = 1
    for i in top_10:
        i['rank'] = rank
        rank += 1

    context = {
        "film": film,
        "series": series,
        "top_10": top_10
    }

    return render(request, 'daftar_trailer.html', context)

def show_tayangan(request):
    if 'username' not in request.session or 'username' not in request.COOKIES:
        return redirect('authentication:landing')
    
    top_10 = query_result(f"""WITH durasi_tayangan AS (
                            SELECT T.id AS id, F.durasi_film AS durasi
                            FROM "TAYANGAN" AS T
                            JOIN "FILM" AS F ON F.id_tayangan = T.id
                            UNION
                            SELECT T.id AS id, AVG(E.durasi) AS durasi
                            FROM "TAYANGAN" AS T
                            JOIN "SERIES" AS S ON S.id_tayangan = T.id
                            JOIN "EPISODE" AS E on E.id_series = T.id
                            GROUP BY T.id
                        ), recent_views AS (
                            SELECT T.id AS id, EXTRACT(EPOCH FROM (RW.end_date_time - RW.start_date_time)) / 60 AS watch_time
                            FROM "TAYANGAN" AS T 
                            JOIN "FILM" AS F ON F.id_tayangan = T.id
                            JOIN "RIWAYAT_NONTON" AS RW ON RW.id_tayangan = T.id
                            WHERE RW.start_date_time >= NOW() - INTERVAL '7 DAYS'
                            UNION
                            SELECT T.id AS id, EXTRACT(EPOCH FROM (RW.end_date_time - RW.start_date_time)) / 60 AS watch_time
                            FROM "TAYANGAN" AS T
                            JOIN "SERIES" AS S ON S.id_tayangan = T.id
                            JOIN "EPISODE" AS E ON E.id_series = T.id
                            JOIN "RIWAYAT_NONTON" AS RW ON RW.id_tayangan = T.id
                            WHERE RW.start_date_time >= NOW() - INTERVAL '7 DAYS'
                        )
                        
                        SELECT T.id, T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer, COUNT(*) as total_view
                        FROM "TAYANGAN" AS T
                        JOIN "durasi_tayangan" AS DT ON DT.id = T.id
                        JOIN "recent_views" AS RV ON RV.id = T.id
                        WHERE RV.watch_time > (0.7 * DT.durasi)
                        GROUP BY T.id, T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer
                        ORDER BY total_view DESC, T.judul ASC
                        LIMIT 10;""")
    
    film = query_result(f"""SELECT T.id, T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer
                            FROM "TAYANGAN" AS T
                            JOIN "FILM" AS F ON F.id_tayangan = T.id;""")

    series = query_result(f"""SELECT T.id, T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer
                            FROM "TAYANGAN" AS T
                            JOIN "SERIES" AS S ON S.id_tayangan = T.id;""")

    paket = query_result(f"""SELECT
                                CASE
                                    WHEN MAX(end_date_time) > CURRENT_DATE THEN 1
                                    ELSE 0
                                END AS is_valid
                            FROM "TRANSACTION"
                            WHERE username = '{request.COOKIES.get('username')}';""")

    rank = 1
    for i in top_10:
        i['rank'] = rank
        rank += 1

    context = {
        "film": film,
        "series": series,
        "top_10": top_10,
        "paket": paket[0]
    }

    return render(request, 'daftar_tayangan.html', context)

def show_hasil_pencarian_trailer(request, value):
    checked_value = check_string_valid(value)
    tayangan = query_result(f"""SELECT judul, sinopsis_trailer, url_video_trailer, release_date_trailer
                                FROM "TAYANGAN"
                                WHERE judul ILIKE '%{checked_value}%';""")   

    context = {"tayangan": tayangan,
                "searchvalue": value}

    return render(request, 'hasil_pencarian_trailer.html', context)

def show_hasil_pencarian_tayangan(request, value):
    if 'username' not in request.session or 'username' not in request.COOKIES:
        return redirect('authentication:landing')
    
    checked_value = check_string_valid(value)
    tayangan = query_result(f"""SELECT id, judul, sinopsis_trailer, url_video_trailer, release_date_trailer
                                FROM "TAYANGAN"
                                WHERE judul ILIKE '%{checked_value}%';""")
    
    paket = query_result(f"""SELECT
                                 CASE
                                     WHEN MAX(end_date_time) > CURRENT_DATE THEN 1
                                     ELSE 0
                                 END AS is_valid
                             FROM "TRANSACTION"
                             WHERE username = '{request.COOKIES.get('username')}';""")
    
    context = {"tayangan": tayangan,
               "searchvalue": value,
               "paket": paket[0]}

    return render(request, 'hasil_pencarian_tayangan.html', context)

def show_film(request, id):
    if 'username' not in request.session or 'username' not in request.COOKIES:
        return redirect('authentication:landing')

    film = query_result(f"""SELECT T.id, T.judul, T.sinopsis, T.asal_negara, F.url_video_film, F.release_date_film, F.durasi_film, G.genre, C.nama AS nama_sutradara
                              FROM "FILM" AS F
                              JOIN "TAYANGAN" AS T ON T.id = F.id_tayangan
                              LEFT JOIN "GENRE_TAYANGAN" AS G ON G.id_tayangan = F.id_tayangan
                              JOIN "CONTRIBUTORS" AS C ON C.id = T.id_sutradara
                              WHERE F.id_tayangan = '{id}';""")

    pemain = query_result(f"""SELECT C.nama
                              FROM "FILM" AS F
                              JOIN "MEMAINKAN_TAYANGAN" AS MT ON MT.id_tayangan = F.id_tayangan
                              JOIN "CONTRIBUTORS" AS C ON C.id = MT.id_pemain
                              WHERE F.id_tayangan = '{id}';""")
    
    penulis = query_result(f"""SELECT C.nama
                              FROM "FILM" AS F
                              JOIN "MENULIS_SKENARIO_TAYANGAN" AS MST ON MST.id_tayangan = F.id_tayangan
                              JOIN "CONTRIBUTORS" AS C ON C.id = MST.id_penulis_skenario
                              WHERE F.id_tayangan = '{id}';""")
    
    view = query_result(f"""SELECT COUNT(id_tayangan)
                            FROM "RIWAYAT_NONTON"

tayangan/templates/film.html
{% extends 'base-tw.html' %}

{% block meta %}
<title>Film</title>
{% endblock meta %}

{% block content %}
<style>
    .title {
            font-size: xx-large;
            font-weight: 500;
            text-align: center;
            margin-top: 120px;
            margin-bottom: 30px;
    }

    .search-bar {
        text-align: center;
        margin-top: 50px;
        margin-bottom: 30px;
    }

    .btn-group {
        margin-top: 15px;
        margin-bottom: 10px;
    }

    span {
        color: black;
    }

    li {
        color: black;
    }

    h5 {
        font-size: larger;
        margin-top: 15px;
        margin-bottom: 10px;
    }

    a {
        color: blue;
    }

    h2 {
        font-size: x-large;
    }

    .empty {
      margin-top: 30px;
      margin-bottom: 30px;
      text-align: center;
      font-size: large;
      font-weight: 600;
    }

    .slider {
        margin-top: 20px;
        margin-bottom: 10px;
    }

    .message-container {
        margin-top: 30px;
        margin-bottom: 30px;
        text-align: center;
        font-size: large;
        font-weight: 600;
        color: red;
    }
</style>

{% include "navbar.html" %}

<div class="container mt-5">
  <h1 class="title">HALAMAN FILM</h1>
  <div class="col">
    <div class="row-md-8">
      <h2>Judul: <span id="judul">{{ film.judul }}</span></h2>
      {% if released.is_released == 1 %}
      <div class="slider">
        <form id="progressForm" action="{% url 'tayangan:add_tonton' %}" method="post">
            {% csrf_token %}  
            <input type="hidden" name="id" value="{{ film.id }}">
            <input type="hidden" name="tipe" value="film">
            <input type="hidden" name="durasi" value="{{ film.durasi_film }}">
            <label for="progress" class="form-label"><b>Progress:</b></label>
            <input type="range" class="form-range" name="progress" id="progress">
        </form>
      </div>
      {% endif %}
      {% if messages %}
      <div class="message-container">
          <ul class="messages">
              {% for message in messages %}
              {% if 'tonton' in message.tags %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endif %}
              {% endfor %}
          </ul>
      </div>
      {% endif %}
      <div class="btn-group" role="group">
        {% if released.is_released == 1 %}
        <button class="btn btn-primary mb-2" id="btnTonton" onclick="submitProgress()">Tonton</button>
        {% endif %}
    </div>
    <h2>
        <a href="{% url 'tayangan:unduh_tayangan' film.id %}">
            <button class="btn btn-primary mb-2" id="btnUnduh" data-bs-toggle="modal" data-bs-target="#downloadModal" data-id= "{{ film.id }}">Unduh Tayangan</button>
        </a>
    </h2>
    <h2>
        <button class="btn btn-primary mb-2" id="btnFavorit" data-bs-toggle="modal" data-bs-target="#favoriteListModal">Favorit Tayangan</button>
    </h2>
      <p><b>Total View:</b> <span id="totalView">{{ view.count }}</span></p>
      <p><b>Rating Rata-Rata:</b> <span id="rating">{{ rating.avg }}</span></p>
      <p><b>Sinopsis:</b> <span id="sinopsis">{{ film.sinopsis }}</span></p>
      <p><b>Durasi Film:</b> <span id="durasi">{{ film.durasi_film }}</span></p>
      <p><b>Tanggal Rilis Film:</b> <span id="tanggalRilis">{{ film.release_date_film }}</span></p>
      <p><b>URL Film:</b> <a href="{{ film.url_video_film }}" id="urlFilm">{{ film.judul }}</a></p>
      <p><b>Genre:</b> <span id="genre">{{ film.genre }}</span></p>
      <p><b>Asal Negara:</b> <span id="asalNegara">{{ film.asal_negara }}</span></p>
      <p><b>Pemain:</b></p>
      <ul class="list-disc pl-4" id="pemain">
        {% for item in pemain %}
        <li>{{ item.nama }}</li>
        {% endfor %}
      </ul>
      <p><b>Penulis Skenario:</b></p>
      <ul class="list-disc pl-4" id="penulis">
        {% for item in penulis %}
        <li>{{ item.nama }}</li>
        {% endfor %}
      </ul>
      <p><b>Sutradara:</b> <span id="sutradara">{{ film.nama_sutradara }}</span></p>
    </div>

<div class="modal fade" id="favoriteListModal" tabindex="-1" aria-labelledby="favoriteListModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="favoriteListModalLabelTitle">TAMBAH KE DAFTAR FAVORIT MODAL</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <select class="form-select mb-3" id="dropdown-favorite">
                    <option value="select-daftar-favorit">Judul Daftar Favorit: </option>
                    {% for judul_daftar in list_daftar_favorit %}
                    <option value="{{ judul_daftar }}">{{ judul_daftar }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="modal-footer d-flex justify-content-center">
                <a id="link_add_favorite" href="#">
                    <button type="button" class="btn btn-primary" id="button_add_favorite" data-bs-dismiss="modal">Tambah</button>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="downloadModal" tabindex="-1" aria-labelledby="downloadModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="downloadModalLabelTitle">SUKSES MENAMBAHKAN TAYANGAN KE DAFTAR UNDUHAN</h1>
            </div>
            <div class="modal-body" id="downloadModalBody">
                <p>
                </p>
            </div>
            <div class="modal-footer">
                <a href="{% url 'daftar_unduhan:show_download'%}" class="text-white hover:text-gray-300 me-2">
                    <button type="button" class="btn btn-primary mb-2">Daftar Unduhan</button>
                </a>
            </div>
        </div>
    </div>
</div>

    <div class="row-md-4">
        <h2 class="title">BAGIAN ULASAN</h2>
        <div class="form-group">
            <form action="{% url 'tayangan:add_ulasan' %}" method="post">
                {% csrf_token %}  
                <input type="hidden" name="id" value="{{ film.id }}">
                <input type="hidden" name="tipe" value="film">
                <div class="row">
                    <div class="col-md-8">
                        <input type="text" class="form-control mb-2" id="inputUlasan" name="deskripsi" placeholder="Deskripsi Ulasan" maxlength="255" required>
                    </div>
                    <div class="col-md-2">
                        <input type="number" class="form-control mb-2" id="inputRating" name="rating" placeholder="Rating (1-10)" min="1" max="10" required>
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary mb-2" id="btnSubmit">Submit</button>
                    </div>
                </div>
            </form>
        </div>
        {% if messages %}
        <div class="message-container">
            <ul class="messages">
                {% for message in messages %}
                {% if 'ulasan' in message.tags %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <h5><b>Daftar Ulasan:</b></h5>
        <ul class="list-disc pl-4" id="daftarUlasan">
            {% for item in ulasan %}
            <b>Username:</b> {{ item.username }}</br>
            <b>Rating:</b> {{ item.rating }}</br>
            <b>Deskripsi:</b> {{ item.deskripsi }}</br></br>
            {% empty %}
            <div class="empty">Belum ada ulasan</div>
            {% endfor %}
        </ul>
    </div>
  </div>
</div>

<script>
        function submitProgress() {
            document.getElementById("progressForm").submit();
        }

        document.getElementById("btnUnduh").addEventListener("click", function () {
            var date = new Date();
            date.setDate(date.getDate() + 7);
            document.getElementById("downloadModalBody").innerHTML = "Selamat! Anda telah berhasil mengunduh " + document.getElementById("judul").innerHTML + " dan akan berlaku hingga " + date.toLocaleDateString('en-GB', { day: 'numeric', month: 'numeric', year: 'numeric' }) + ". Cek informasi selengkapnya pada halaman daftar unduhan.";
            
        });

        document.getElementById("btnFavorit").addEventListener("click", function () {
            console.log("Menambahkan ke favorit...");
        });

        document.getElementById('button_add_favorite').addEventListener('click', function() {
        // Get the selected value from the dropdown
        var dropdown = document.getElementById('dropdown-favorite');
        var selectedJudul = dropdown.options[dropdown.selectedIndex].value;
        
        var url = encodeURIComponent(selectedJudul) + "/";

        document.getElementById('link_add_favorite').setAttribute('href', url);
    });

        document.getElementById("btnSubmit").addEventListener("click", function() {
            var inputRating = document.getElementById("inputRating").value;
            if (isNaN(inputRating) || inputRating < 0 || inputRating > 10) {
                alert("Rating harus dalam rentang 0-10");
                return false;
            }
            console.log("Rating: " + inputRating);
        });
</script>
{% endblock content %}

tayangan/templates/series.html
{% extends 'base-tw.html' %}

{% block meta %}
<title>Series</title>
{% endblock meta %}

{% block content %}
<style>
    .title {
            font-size: xx-large;
            font-weight: 500;
            text-align: center;
            margin-top: 120px;
            margin-bottom: 30px;
    }

    .search-bar {
        text-align: center;
        margin-top: 50px;
        margin-bottom: 30px;
    }

    .btn-group {
        margin-top: 10px;
        margin-bottom: 10px;
    }

    span {
        color: black;
    }

    li {
        color: black;
    }

    h5 {
        font-size: larger;
        margin-top: 15px;
        margin-bottom: 10px;
    }

    a {
        color: blue;
    }
    
    h2 {
        font-size: x-large;
        margin-bottom: 10px;
    }

    .empty {
      margin-top: 30px;
      margin-bottom: 30px;
      text-align: center;
      font-size: large;
      font-weight: 600;
    }

    .message-container {
        margin-top: 30px;
        margin-bottom: 30px;
        text-align: center;
        font-size: large;
        font-weight: 600;
        color: red;
    }
</style>

{% include "navbar.html" %}
<div class="container mt-5">
  <h1 class="title">HALAMAN SERIES</h1>
  <div class="col">
    <div class="row-md-8">
      <h2>Judul: <span id="judul">{{ series.judul }}</span></h2>
      <h2>
          <a href="{% url 'tayangan:unduh_tayangan' series.id %}" >
              <button class="btn btn-primary mb-2" id="btnUnduh" data-bs-toggle="modal" data-bs-target="#downloadModal" data-id= "{{ series.id }}">Unduh Tayangan</button>
          </a>

      </h2>
      <h2>
            <button class="btn btn-primary mb-2" id="btnFavorit" data-bs-toggle="modal" data-bs-target="#favoriteListModal" data-judul_tayangan="{{ series.judul }}">Favorit Tayangan
      </h2>
      <p><b>Episode:</b></p>
      <ul class="list-disc pl-4" id="episode">
        {% for item in episode %}
        <li><a href="/tayangan/series/{{ item.url }}">{{ item.sub_judul }}</a></li>
        {% endfor %}
      </ul>
      <p><b>Total View:</b> <span id="totalView">{{ view.count }}</span></p>
      <p><b>Rating Rata-Rata:</b> <span id="rating">{{ rating.avg }}</span></p>
      <p><b>Sinopsis:</b> <span id="sinopsis">{{ series.sinopsis }}</span></p>
      <p><b>Genre:</b> <span id="genre">{{ series.genre }}</span></p>
      <p><b>Asal Negara:</b> <span id="asalNegara">{{ series.asal_negara }}</span></p>
      <p><b>Pemain:</b></p>
      <ul class="list-disc pl-4" id="pemain">
        {% for item in pemain %}
        <li>{{ item.nama }}</li>
        {% endfor %}
      </ul>
      <p><b>Penulis Skenario:</b></p>
      <ul class="list-disc pl-4" id="penulis">
        {% for item in penulis %}
        <li>{{ item.nama }}</li>
        {% endfor %}
      </ul>
      <p><b>Sutradara:</b> <span id="sutradara">{{ series.nama_sutradara }}</span></p>
    </div>
    <div class="modal fade" id="favoriteListModal" tabindex="-1" aria-labelledby="favoriteListModalLabel" aria-hidden="true" data-bs-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="favoriteListModalLabelTitle">TAMBAH KE DAFTAR FAVORIT MODAL</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <select class="form-select mb-3" id="dropdown-favorite">
                        <option value="select-daftar-favorit">Judul Daftar Favorit: </option>
                        {% for judul_daftar in list_daftar_favorit %}
                        <option value="{{ judul_daftar }}">{{ judul_daftar }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="modal-footer d-flex justify-content-center">
                    <a id="link_add_favorite" href="">
                        <button type="button" class="btn btn-primary" id="button_add_favorite" data-bs-dismiss="modal">Tambah</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal fade" id="downloadModal" tabindex="-1" aria-labelledby="downloadModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="downloadModalLabelTitle">SUKSES MENAMBAHKAN TAYANGAN KE DAFTAR UNDUHAN</h1>
                </div>
                <div class="modal-body" id="downloadModalBody">
                    <p>
                    </p>
                </div>
                <div class="modal-footer">
                    <a href="{% url 'daftar_unduhan:show_download'%}" class="text-white hover:text-gray-300 me-2">
                        <button type="button" class="btn btn-primary mb-2">Daftar Unduhan</button>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="row-md-4 ulasan">
        <h2 class="title">BAGIAN ULASAN</h2>
        <div class="form-group">
            <form action="{% url 'tayangan:add_ulasan' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ series.id }}">
                <input type="hidden" name="tipe" value="series">
                <div class="row">
                    <div class="col-md-8">
                        <input type="text" class="form-control mb-2" id="inputUlasan" name="deskripsi" placeholder="Deskripsi Ulasan" maxlength="255" required>
                    </div>
                    <div class="col-md-2">
                        <input type="number" class="form-control mb-2" id="inputRating" name="rating" placeholder="Rating (1-10)" min="1" max="10" required>
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary mb-2" id="btnSubmit">Submit</button>
                    </div>
                </div>
            </form>
        </div>
        {% if messages %}
        <div class="message-container">
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <h5><b>Daftar Ulasan:</b></h5>
        <ul class="list-disc pl-4" id="daftarUlasan">
            {% for item in ulasan %}
            <b>Username:</b> {{ item.username }}</br>
            <b>Rating:</b> {{ item.rating }}</br>
            <b>Deskripsi:</b> {{ item.deskripsi }}</br></br>
            {% empty %}
            <div class="empty">Belum ada ulasan</div>
            {% endfor %}
        </ul>
    </div>
</div>

<script>
        document.getElementById("btnUnduh").addEventListener("click", function () {
            var date = new Date();
            date.setDate(date.getDate() + 7);
            document.getElementById("downloadModalBody").innerHTML = "Selamat! Anda telah berhasil mengunduh " + document.getElementById("judul").innerHTML + " dan akan berlaku hingga " + date.toLocaleDateString('en-GB', { day: 'numeric', month: 'numeric', year: 'numeric' }) + ". Cek informasi selengkapnya pada halaman daftar unduhan.";
        });
    
        document.getElementById('button_add_favorite').addEventListener('click', function() {
            var dropdown = document.getElementById('dropdown-favorite');
            var selectedJudul = dropdown.options[dropdown.selectedIndex].value;      
            var url = encodeURIComponent(selectedJudul) + "/";
            document.getElementById('link_add_favorite').setAttribute('href', url);     
        });
    
        document.getElementById("btnSubmit").addEventListener("click", function() {
            var inputRating = document.getElementById("inputRating").value;
            if (isNaN(inputRating) || inputRating < 0 || inputRating > 10) {
                alert("Rating harus dalam rentang 0-10");
                return false;
            }
    
            console.log("Rating: " + inputRating);
        });
</script>
{% endblock content %}